### ISSUE TITLE
digital twins.

### ISSUE THREAD

**Issue by gedw99** [viamrobotics/motion-testing#16]
the idea is that the messages going to the physical and gui version are digital twins.

The easiest way i know to do this is to use a simple golang gui that is cross platform, including web.

If there is interest in this i could help with this work.

The golang gui can use the same scene files and stl files i think too.  There are golang libs that can render the STL and also golang gui windows that can consume this to give a cross platform tester.

**Comment by gedw99** [comment]
https://github.com/rajveermalviya/go-webgpu provides the basis of a 2d and 3d window that works on any platform.

But overlaid with gioui for the native keyboard and mouse events off the window.

**Comment by tessavitabile** [comment]
Hi @gedw99,

I think what you might be looking for is a motion service card on the remote control page for a robot, which allows you to visualize the current configuration of an arm and control the arm. This is tracked in https://viam.atlassian.net/browse/RSDK-3239, which is currently on our roadmap. Please follow that ticket for updates.

Best,
Tess
